# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-qWuR2vMKzM2u1PjudJErQ3Fz7L6hwiO
"""

# ЗАВДАННЯ 1
# використовуючи цикл 'for' записати в файл 'my_file.txt` 10 рядків:
#   1-й рядок

with open("my_file.txt", "w") as file:
    for i in range(1, 11):
        file.write(f"{i}-й рядок\n")

# ЗАВДАННЯ 2
# прочитати та вивести перші 5 записів з файла `my_file.txt`

with open('my_file.txt', 'r') as f:
    lines = f.readlines()

for line in lines[:5]:
    print(line.strip())

# ЗАВДАННЯ 3
# виконати Завдання 2 з допомогою менеджера контекста

with open('my_file.txt', 'r') as f:
    for i in range(5):
        line = f.readline()
        print(line.strip())